### PR TITLE
feat(#174): arc github lock

### LINKED ISSUE #174: can't register user
I sent this request to `POST http://localhost:3000/users`:

```json
{
  "login": "test",
  "extra": {},
  "repos": [
    {
      "name": "test",
      "private": false
    }
  ]
}
```

Application logs tell me that is registered:

```text
2024-09-26T09:01:41.074925Z  INFO fakehub_server::objects::user: Registered @test
2024-09-26T09:01:41.075019Z  INFO fakehub_server::handlers::register_user: New user is here. Hello @test
```

However, when I open `http://localhostl:3000/users/test` I getting

```json
{
"documentation_url": "https://github.com/h1alexbel/fakehub",
"message": "Not Found",
"status": "404"
}
```

When I open `http://localhost:3000/users` I don't getting it too:

```json
[
  {
    "id": 1,
    "login": "jeff"
  },
  {
    "id": 2,
    "login": "h1alexbel"
  }
]
```

### PR DESCRIPTION
**Pull request by h1alexbel**
In this pull I've fixed bug with broken user registration via `Arc<Mutex<GitHub>>`, introduced new tests to catch this problem in the future.

closes #174 
History:
- **feat(#174): works**
- **feat(#174): enable tests**
- **feat(#174): enable repo tests**
- **feat(#174): enable fakehub tests**
- **feat(#174): enable doc tests**
- **feat(#174): clean for check**
- **feat(#174): test**
- **feat(#174): registers_with_extra_fields**

---

## PR-Codex overview
This PR focuses on enhancing thread safety in the `FakeHub` structure by using `Arc<Mutex<GitHub>>`, ensuring concurrent access is managed properly. Additionally, it refactors various functions and updates user handling to improve reliability and maintainability.

### Detailed summary
- Changed `github` in `FakeHub` to `Arc<Mutex<GitHub>>` for thread safety.
- Updated `main()` method to return `Arc<Mutex<GitHub>>`.
- Refactored user handling in multiple handlers to lock the GitHub instance before accessing users.
- Modified `Coordinates` struct to hold a reference to `FakeHub`.
- Adjusted method signatures to accept references where appropriate.
- Enhanced tests to validate user registration and properties.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by l3r8yJ** [comment]
@h1alexbel can we wait this [pr](https://github.com/h1alexbel/fakehub/pull/164) before merging this one?

**Comment by h1alexbel** [comment]
@l3r8yJ I think yes, if it would be fast to merge `types` PR

**Comment by h1alexbel** [comment]
@l3r8yJ take a look, please

**Comment by h1alexbel** [comment]
@l3r8yJ take a look, please

**Comment by h1alexbel** [comment]
@l3r8yJ take a look, please

**Comment by h1alexbel** [comment]
@l3r8yJ take a look, please

**Comment by 0crat** [comment]
@h1alexbel Hey there, awesome work on your contribution! 👍 You've earned +4 points, which breaks down like this: +4 base points, +6 for your 139 [hits-of-code](https://www.yegor256.com/2014/11/14/hits-of-code.html) (nice job!), but -16 because there wasn't a code review (oops!). We bumped it up by +9 to keep you motivated. Your total balance is now [+63](https://www.h1alexbel.xyz/fakehub/zerocracy/fakehub-vitals.html). Remember, code reviews are super important - they can boost your points and improve code quality. Keep the contributions coming and aim for that sweet spot of 200-800 hits-of-code for max points! [Keep up](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) the great work!

**Pull request merged**
