### PR TITLE
feat(#147): GET /users

### PR DESCRIPTION
**Pull request by h1alexbel**
In this pull, I've implemented mock version of https://api.github.com/users endpoint.

closes: #147
History:
- **feat(#147): json<vec<value>>**
- **feat(#147): sort_by_key**
- **feat(#147): jeff comes first**

---

## PR-Codex overview
This PR updates the server to include a new `users` module and endpoint, allowing retrieval of all GitHub users.

### Detailed summary
- Added `users` module to handle all GitHub users.
- Updated `FakeHub` to include multiple users with additional data.
- Implemented endpoint to retrieve and sort all users by id.
- Added tests for the new `users` endpoint functionality.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by h1alexbel** [comment]
@rultor try merge

**Comment by h1alexbel** [comment]
@rultor try to merge

**Comment by h1alexbel** [comment]
@rultor try to merge

**Comment by 0crat** [comment]
@h1alexbel Hey there! 👋 Thanks for your code contribution! You've earned +4 points this time. Here's the breakdown: +4 base points, -16 for no code review (ouch!), but we bumped it back up to +4 to keep you motivated. Remember, code reviews are crucial - they can boost your points and improve code quality. Also, more [hits-of-code](https://www.yegor256.com/2014/11/14/hits-of-code.html) (over 20) can increase your bonus next time. [Keep](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) the contributions coming! Your current balance is [+20](https://www.h1alexbel.xyz/fakehub/zerocracy/fakehub-vitals.html). Let's aim for more points on your next submission! 💪

**Pull request merged**
