### PR TITLE
chore: code-review-quality workflow

### PR DESCRIPTION
**Pull request by h1alexbel**
code review quality control

---

## PR-Codex overview
This PR adds a code review workflow that triggers on submitted pull request reviews and runs a code review action when the review is approved.

### Detailed summary
- Added MIT License to the workflow file
- Defined a code review workflow triggered by approved pull request reviews
- Configured the workflow to run a specific code review action with necessary tokens and model information

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by h1alexbel** [comment]
@rultor merge

**Comment by h1alexbel** [comment]
@rultor merge again

**Comment by h1alexbel** [comment]
@rultor merge

**Comment by l3r8yJ** [comment]
@h1alexbel I think for a while we can do manual mergers as we have CI pipeline

**Comment by h1alexbel** [comment]
ref for https://github.com/h1alexbel/fakehub/issues/11

**Pull request merged**
