### PR TITLE
feat(#1): more ghas

### PR DESCRIPTION
**Pull request by h1alexbel**
ref #1

---

## PR-Codex overview
This PR updates license headers and adds code quality tools to the project.

### Detailed summary
- Updated license headers in various files
- Added `.pdd` file with code quality rules
- Added `clippy.toml` for linting rules
- Updated `main.rs` with license header
- Added license headers to `.markdownlint.yml`, `.0pdd.yml`, `.yamllint.yml`, `.rultor.yml`
- Added workflows for `xcop`, `typos`, `pdd` with license headers

> The following files were skipped due to too many changes: `.github/workflows/pdd.yml`, `.github/workflows/yamllint.yml`, `.github/workflows/reports-check.yml`, `.github/workflows/actionlint.yml`, `.github/workflows/cargo.yml`, `.github/workflows/license.yml`, `.github/workflows/year.yml`, `Cargo.toml`, `LICENSE.txt`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by h1alexbel** [comment]
@l3r8yJ take a look, please

**Review by l3r8yJ — APPROVED** [review]
@h1alexbel looks good to me!

**Comment by l3r8yJ** [comment]
@h1alexbel can you try to `@rultor merge`?

**Comment by h1alexbel** [comment]
@l3r8yJ we can't merge it with `@rultor` since we modified `.rultor.yml` in this pr

**Pull request merged**
