### PR TITLE
feat(#44): features, opt clap

### LINKED ISSUE #44: features block in `Cargo.toml`
add smth like this

https://github.com/cocogitto/cocogitto/blob/72e1f8624939a089414aa28418bd2249972fac23/Cargo.toml#L61

### PR DESCRIPTION
**Pull request by h1alexbel**
@l3r8yJ take a look, please.

closes #44

---

## PR-Codex overview
The focus of this PR is to add optional dependencies for CLI features and define feature flags for different CLI components.

### Detailed summary
- Added optional dependencies for `clap_complete`, `clap_mangen`, and `clap_complete_nushell`
- Defined feature flags for `cli` with specific dependencies for different CLI components

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Review by l3r8yJ — APPROVED** [review]
@h1alexbel looks good to me!

**Comment by h1alexbel** [comment]
@l3r8yJ let's try this rultor image: `  image: yegor256/rultor-image:1.23.1`

**Comment by h1alexbel** [comment]
@rultor merge

**Comment by h1alexbel** [comment]
nice, this image works!
@l3r8yJ FYI

**Pull request merged**
